# Generated by Django 5.1 on 2024-08-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Artist's name", max_length=100)),
                ('genre', models.CharField(help_text='Music genre of the artist', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the song', max_length=100)),
                ('duration', models.DurationField(help_text='Duration of the song in HH:MM:SS format')),
                ('release_date', models.DateField(blank=True, help_text='Release date of the song', null=True)),
                ('artist', models.ForeignKey(help_text='Artist who performed the song', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='museic.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the playlist', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the playlist', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the playlist was created')),
                ('songs', models.ManyToManyField(help_text='Songs included in the playlist', related_name='playlists', to='museic.song')),
            ],
        ),
    ]
