# Generated by Django 5.1 on 2024-08-28 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the album', max_length=100)),
                ('release_date', models.DateField(blank=True, help_text='Release date of the album', null=True)),
                ('artist', models.ForeignKey(help_text='Artist who created the album', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='museic.artist')),
            ],
        ),
    ]
