# Generated by Django 5.1 on 2024-09-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museic', '0003_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, help_text='Audio file of the song', null=True, upload_to='songs/'),
        ),
    ]
