# Generated by Django 5.1 on 2024-09-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museic', '0004_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(help_text='Artist who performed the song', max_length=100),
        ),
    ]
