# Generated by Django 5.1 on 2024-09-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museic', '0005_alter_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the song', null=True, upload_to='covers/'),
        ),
    ]
