# Generated by Django 5.1.1 on 2024-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museic', '0006_song_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of the artist', null=True, upload_to='artists/'),
        ),
    ]
