# Generated by Django 5.1.1 on 2024-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museic', '0007_artist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the album', null=True, upload_to='albums/'),
        ),
    ]
