# Generated by Django 5.1 on 2024-10-07 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museic', '0008_album_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='photo',
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(help_text='Artist who performed the song', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='museic.artist'),
        ),
    ]
