# Generated by Django 5.1 on 2024-10-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museic', '0009_remove_album_cover_image_remove_artist_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image of the album', null=True, upload_to='albums/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of the artist', null=True, upload_to='artists/'),
        ),
    ]
