# Generated by Django 5.1 on 2024-10-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museic', '0011_playlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
    ]
