# Generated by Django 5.1 on 2024-10-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museic', '0013_playlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(help_text='Albümü yaratan sanatçı', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='museic.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Albüm kapağı', null=True, upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, help_text='Albümün çıkış tarihi', null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(help_text='Albümün adı', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(help_text='Sanatçının müzik türü', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(help_text='Sanatçının adı', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, help_text='Sanatçının fotoğrafı', null=True, upload_to='artists/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Çalma listesinin oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, help_text='Çalma listesinin açıklaması', null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(help_text='Çalma listesinin adı', max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(help_text='Çalma listesine eklenen şarkılar', related_name='playlists', to='museic.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, help_text='Şarkının bulunduğu albüm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='museic.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(help_text='Şarkıyı seslendiren sanatçı', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='museic.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Şarkının kapak resmi', null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(help_text='Şarkının süresi HH:MM:SS formatında'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, help_text='Şarkının ses dosyası', null=True, upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(blank=True, help_text='Şarkının çıkış tarihi', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(help_text='Şarkının adı', max_length=100),
        ),
    ]
