name: museic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1  
  http: ^1.2.2
  flutter_bloc: ^8.0.0
  audioplayers: ^6.1.0
  google_fonts: ^6.2.1
  sizer: ^3.0.4
  palette_generator: ^0.3.3+4

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/spotify_logo.png"
  adaptive_icon_background: "#000000"  # Siyah arka plan
  adaptive_icon: "#000000"  # Siyah arka plan
  adaptive_icon_foreground: "assets/images/spotify_logo.png"  # Öne çıkan ikon

flutter_native_splash:
  color: "#000000"  # Siyah arka plan
  image: assets/images/spotify_logo.png  # Logonuzun yolu
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
    - assets/musics/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
